-- MySQL Script generated by MySQL Workbench
-- Sat Jan  7 08:35:49 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema organic_integrity
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema organic_integrity
-- -----------------------------------------------------
-- CREATE SCHEMA IF NOT EXISTS `organic_integrity` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `organic_integrity` ;

-- -----------------------------------------------------
-- Table `organic_integrity`.`organic_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `organic_integrity`.`organic_item` ;

-- -----------------------------------------------------
-- Table `organic_integrity`.`organic_operation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `organic_integrity`.`organic_operation` ;

CREATE TABLE IF NOT EXISTS `organic_integrity`.`organic_operation` (
  `op_certifierName` TEXT NULL DEFAULT NULL,
  `op_nopOpID` BIGINT NOT NULL,
  `op_name` TEXT NULL DEFAULT NULL,
  `op_otherNames` DOUBLE NULL DEFAULT NULL,
  `op_clientID` TEXT NULL DEFAULT NULL,
  `op_contFirstName` TEXT NULL DEFAULT NULL,
  `op_contLastName` TEXT NULL DEFAULT NULL,
  `op_status` TEXT NULL DEFAULT NULL,
  `op_statusEffectiveDate` DATETIME NULL DEFAULT NULL,
  `op_nopAnniversaryDate` DATETIME NULL DEFAULT NULL,
  `op_lastUpdatedDate` DATETIME NULL DEFAULT NULL,
  `opSC_CR` TEXT NULL DEFAULT NULL,
  `opSC_CR_ED` DATETIME NULL DEFAULT NULL,
  `opSC_LS` TEXT NULL DEFAULT NULL,
  `opSC_LS_ED` DATETIME NULL DEFAULT NULL,
  `opSC_WC` TEXT NULL DEFAULT NULL,
  `opSC_WC_ED` DATETIME NULL DEFAULT NULL,
  `opSC_HANDLING` TEXT NULL DEFAULT NULL,
  `opSC_HANDLING_ED` DATETIME NULL DEFAULT NULL,
  `opPA_line1` TEXT NULL DEFAULT NULL,
  `opPA_line2` TEXT NULL DEFAULT NULL,
  `opPA_city` TEXT NULL DEFAULT NULL,
  `opPA_state` TEXT NULL DEFAULT NULL,
  `opPA_country` TEXT NULL DEFAULT NULL,
  `opPA_zip` TEXT NULL DEFAULT NULL,
  `opPA_countyCode` DOUBLE NULL DEFAULT NULL,
  `opPA_county` TEXT NULL DEFAULT NULL,
  `opMA_line1` TEXT NULL DEFAULT NULL,
  `opMA_line2` TEXT NULL DEFAULT NULL,
  `opMA_city` TEXT NULL DEFAULT NULL,
  `opMA_state` TEXT NULL DEFAULT NULL,
  `opMA_country` TEXT NULL DEFAULT NULL,
  `opMA_zip` TEXT NULL DEFAULT NULL,
  `opMA_countyCode` DOUBLE NULL DEFAULT NULL,
  `opMA_county` TEXT NULL DEFAULT NULL,
  `op_phone` TEXT NULL DEFAULT NULL,
  `op_email` TEXT NULL DEFAULT NULL,
  `op_url` TEXT NULL DEFAULT NULL,
  `opEx_broker` TEXT NULL DEFAULT NULL,
  `opEx_csa` TEXT NULL DEFAULT NULL,
  `opEx_copacker` TEXT NULL DEFAULT NULL,
  `opEx_dairy` TEXT NULL DEFAULT NULL,
  `opEx_distributor` TEXT NULL DEFAULT NULL,
  `opEx_marketerTrader` TEXT NULL DEFAULT NULL,
  `opEx_restaurant` TEXT NULL DEFAULT NULL,
  `opEx_retailer` TEXT NULL DEFAULT NULL,
  `opEx_poultry` TEXT NULL DEFAULT NULL,
  `opEx_privateLabeler` TEXT NULL DEFAULT NULL,
  `opEx_slaughterHouse` TEXT NULL DEFAULT NULL,
  `opEx_storage` TEXT NULL DEFAULT NULL,
  `opEx_growerGroup` TEXT NULL DEFAULT NULL,
  `opCert_url` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY `idx_operation` (`op_nopOpID`)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `organic_integrity`.`organic_item` (
  `index` BIGINT NULL DEFAULT NULL,
  `ci_artID` BIGINT NOT NULL AUTO_INCREMENT,  -- Artificial primary key added in.
  `ci_nopOpID` BIGINT NOT NULL,
  `ci_certNumber` TEXT NULL DEFAULT NULL,
  `ci_nopScope` TEXT NULL DEFAULT NULL,
  `ci_nopCategory` TEXT NULL DEFAULT NULL,
  `ci_nopCatID` DOUBLE NULL DEFAULT NULL,
  `ci_nopCatName` TEXT NULL DEFAULT NULL,
  `ci_nopItemID` DOUBLE NULL DEFAULT NULL,
  `ci_itemList` TEXT NULL DEFAULT NULL,
  `ci_varieties` TEXT NULL DEFAULT NULL,
  `ci_status` TEXT NULL DEFAULT NULL,
  `ci_statusEffectiveDate` DATETIME NULL DEFAULT NULL,
  `ci_organic100` TEXT NULL DEFAULT NULL,
  `ci_organic` TEXT NULL DEFAULT NULL,
  `ci_madeWithOrganic` TEXT NULL DEFAULT NULL,
  PRIMARY KEY `ix_organic_item_index` (`ci_artID`),
  INDEX `idx_item_operation` (`ci_nopOpID` ASC) VISIBLE,
  FOREIGN KEY (`ci_nopOpID`) REFERENCES `organic_integrity`.`organic_operation` (`op_nopOpID`) 
    ON DELETE CASCADE
)

ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
